defaults:
  - layer: s4

_name_: model
prenorm: true
transposed: false
n_layers: 4 #8
d_model: 64 #128 #1152 highest for mnist
bidirectional: false  # Different from inner layer's bidirectional, just concatenate a forward and reverse layer
residual: R
pool:
  _name_: pool
  stride: 1
  expand: null
norm: layer
dropout: 0.5 #0.3 #0.25 #0.1
tie_dropout: false
track_norms: true # Logs to wandb

# Optional encoder/decoder, e.g. add positional embeddings or padding masks
encoder: null
decoder: null
