batch_size: 64 #128 #64 #128 #1 #75% 64 #50
num_workers: 8 #75% 8  #4
pin_memory: True #False #True
drop_last: True # We set this to true because of the recurrent state mechanism

train_resolution: 1
eval_resolutions:
  - 1
