- _name_: mha
  causal: false #true
  n_heads: 4 #8
  dropout: null
  bias: True
  add_bias_kv: False
  add_zero_attn: False
  kdim: null
  vdim: null
- _name_: ffn
  expand: 4
  activation: relu #gelu
  dropout: 0.3 #0.5 #0.3 #0.25 #${...dropout} # Same as null
